### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by StarryVae** [efficient/HERD#1]
I have done everything following the README, but it prints "Wait for iter 1 at client 0 GET = 0" all the time.

**Comment by anujkaliaiitd** [comment]
This code is not maintained anymore. Please use the new and improved (up to 83% faster) version of HERD from our USENIX ATC 16 paper. The code is available: https://github.com/efficient/rdma_bench/tree/master/herd

I am happy to help with issues on that repository.

**Comment by StarryVae** [comment]
Thanks for your reply!
